# Generated by Django 2.1.1 on 2018-09-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('#940f15', '#940f15'), ('#a4b6c1', '#a4b6c1'), ('#2e598f', '#2e598f'), ('#0c2141', '#0c2141')], default=('#a4b6c1', '#a4b6c1'), max_length=7),
        ),
    ]
