# Generated by Django 2.1.1 on 2018-09-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0002_auto_20180915_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='discus_id',
            field=models.CharField(default='alibaba', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('#940f15', '#940f15'), ('#a4b6c1', '#a4b6c1'), ('#2e598f', '#2e598f'), ('#0c2141', '#0c2141')], default=('#0c2141', '#0c2141'), max_length=7),
        ),
    ]
