# Generated by Django 2.1.1 on 2018-09-16 11:41

import cis.submodels.discus
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cis', '0003_auto_20180915_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='post',
        ),
        migrations.AddField(
            model_name='board',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('#940f15', '#940f15'), ('#2e598f', '#2e598f'), ('#0c2141', '#0c2141')], default=cis.submodels.discus.Post.color_picker, max_length=7),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
