# Generated by Django 2.1.1 on 2019-01-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('Applicant', 'Applicant'), ('Cadet', 'Cadet'), ('Instructor', 'Instructor'), ('Permanent Party', 'Permanent Party'), ('Coach', 'Coach'), ('Medical Staff', 'Medical Staff'), ('Facilities', 'Facilities'), ('Alumni', 'Alumni'), ('Other', 'Other'), ('None', 'None')], default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='has_attended',
            field=models.BooleanField(default=False),
        ),
    ]
