# Generated by Django 2.1.1 on 2018-10-22 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('military', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='members',
            field=models.ManyToManyField(related_name='units', to=settings.AUTH_USER_MODEL),
        ),
    ]
