# Generated by Django 2.1.1 on 2019-02-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='num_vote_down',
        ),
        migrations.RemoveField(
            model_name='board',
            name='num_vote_up',
        ),
        migrations.RemoveField(
            model_name='board',
            name='vote_score',
        ),
        migrations.AddField(
            model_name='post',
            name='num_vote_down',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='num_vote_up',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='vote_score',
            field=models.IntegerField(db_index=True, default=0),
        ),
    ]
