# Generated by Django 2.1.1 on 2018-10-22 23:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_Excusal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
                ('approved_time', models.DateTimeField(blank=True)),
                ('reason', models.TextField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('restrictions', models.CharField(blank=True, max_length=300)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_excusal_aproved', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_excusal_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(related_name='admin_excusal_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Day_Type',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Day_Type_Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FM18_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Form_18',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('creator', models.ForeignKey(limit_choices_to={'is_MDG': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_18_created', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(limit_choices_to={'is_Cadet': True}, on_delete=django.db.models.deletion.CASCADE, related_name='form_18_member', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
                ('type', models.ManyToManyField(to='cas.FM18_Type')),
            ],
        ),
        migrations.CreateModel(
            name='Period_Slot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('from_time', models.TimeField()),
                ('to_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='SCA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('created_time', models.DateTimeField()),
                ('approved_time', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=128)),
                ('summary', models.TextField()),
                ('is_emergency', models.BooleanField(default=False)),
                ('approver', models.ForeignKey(blank=True, limit_choices_to={'is_SCA': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sca_approved', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sca_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SCA_Restriction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restriction', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('day_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cas.Day_Type')),
            ],
        ),
        migrations.AddField(
            model_name='sca',
            name='restrictions',
            field=models.ManyToManyField(blank=True, to='cas.SCA_Restriction'),
        ),
        migrations.AddField(
            model_name='period_slot',
            name='cas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='cas.Schedule'),
        ),
    ]
