# Generated by Django 2.1.1 on 2018-09-25 23:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('summary', models.TextField()),
                ('academic_credit_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('military_credit_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('athletic_credit_hours', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_grade', models.DecimalField(decimal_places=4, max_digits=6)),
                ('letter_grade_current', models.CharField(choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'Fail'), ('IC', 'Incomplete Controllable'), ('IU', 'Incomplete Uncontrollable'), ('W', 'Withdrawn'), ('WP', 'Withdrawn Passing'), ('WF', 'Withdrawn Failing'), ('P', 'Passing'), ('N', 'No Grade')], max_length=2)),
                ('letter_grade_final', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'Fail'), ('IC', 'Incomplete Controllable'), ('IU', 'Incomplete Uncontrollable'), ('W', 'Withdrawn'), ('WP', 'Withdrawn Passing'), ('WF', 'Withdrawn Failing'), ('P', 'Passing'), ('N', 'No Grade')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('summary', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('formal_name', models.CharField(max_length=300)),
                ('informal_name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Core', 'Core'), ('Scholars', 'Scholars'), ('Military', 'Military'), ('Athletic', 'Athletic')], max_length=100)),
                ('summary', models.TextField()),
                ('credit_requirement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Program_Schedule_Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('sequence_number', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Term_Instance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('GPA_Final', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('MPA_Final', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('PEA_Final', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('program_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_instances', to='academics.Program_Schedule')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Term')),
            ],
        ),
        migrations.CreateModel(
            name='Term_Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('term_sequence_number', models.IntegerField()),
                ('courses', models.ManyToManyField(to='academics.Course')),
            ],
        ),
    ]
