# Generated by Django 2.1.7 on 2019-03-14 20:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_grade', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
                ('letter_grade', models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'Fail'), ('IC', 'Incomplete Controllable'), ('IU', 'Incomplete Uncontrollable'), ('W', 'Withdrawn'), ('WP', 'Withdrawn Passing'), ('WF', 'Withdrawn Failing'), ('P', 'Pass'), ('N', 'No Grade')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('abbreviation', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('academic_credit_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('military_credit_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('athletic_credit_hours', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Requirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('abbreviation', models.CharField(max_length=10)),
                ('summary', models.TextField()),
                ('is_archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('formal_name', models.CharField(max_length=300)),
                ('informal_name', models.CharField(max_length=300)),
                ('type', models.CharField(choices=[('Major', 'Major'), ('Minor', 'Minor'), ('Core', 'Core'), ('Scholars', 'Scholars'), ('Military', 'Military'), ('Athletic', 'Athletic')], max_length=100)),
                ('summary', models.TextField()),
                ('credit_requirement', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('number_grade', models.DecimalField(blank=True, decimal_places=4, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('max_students', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
            ],
        ),
    ]
