# Generated by Django 2.1.1 on 2018-09-25 23:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program_schedule',
            name='profile',
            field=models.OneToOneField(blank=True, limit_choices_to={'is_Cadet': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='cadets',
            field=models.ManyToManyField(related_name='programs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.Department'),
        ),
        migrations.AddField(
            model_name='department',
            name='admins',
            field=models.ManyToManyField(related_name='department_faculty', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='instructors',
            field=models.ManyToManyField(related_name='department_instructor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course_requirement',
            name='courses_satisfy',
            field=models.ManyToManyField(related_name='requirements_satisfied', to='academics.Course'),
        ),
        migrations.AddField(
            model_name='course_requirement',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Program'),
        ),
        migrations.AddField(
            model_name='course_instance',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Course'),
        ),
        migrations.AddField(
            model_name='course_instance',
            name='program_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.Program_Schedule'),
        ),
        migrations.AddField(
            model_name='course_instance',
            name='term_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_instances', to='academics.Term_Instance'),
        ),
        migrations.AddField(
            model_name='course',
            name='coerequisites',
            field=models.ManyToManyField(blank=True, related_name='_course_coerequisites_+', to='academics.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(related_name='instructed_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='managers',
            field=models.ManyToManyField(related_name='managed_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='_course_prerequisites_+', to='academics.Course'),
        ),
        migrations.AddField(
            model_name='course',
            name='terms_offered',
            field=models.ManyToManyField(blank=True, related_name='courses', to='academics.Term'),
        ),
    ]
