# Generated by Django 2.1.1 on 2019-01-05 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20181022_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='academics.Department'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='letter_grade_current',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-'), ('D', 'D'), ('F', 'Fail'), ('IC', 'Incomplete Controllable'), ('IU', 'Incomplete Uncontrollable'), ('W', 'Withdrawn'), ('WP', 'Withdrawn Passing'), ('WF', 'Withdrawn Failing'), ('P', 'Passing'), ('N', 'No Grade')], max_length=2, null=True),
        ),
    ]
