# Generated by Django 2.1.1 on 2018-09-29 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20180925_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
