# Generated by Django 2.1.1 on 2019-01-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20190105_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='terms_offered',
            new_name='terms',
        ),
    ]
