# Generated by Django 2.1.1 on 2018-10-02 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_department_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='abbreviation',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
