# Generated by Django 2.1.1 on 2019-01-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20190110_1706'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='instructor',
            new_name='instructors',
        ),
        migrations.AlterField(
            model_name='course',
            name='academic_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='athletic_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='military_credit_hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=3, null=True),
        ),
    ]
