# Generated by Django 2.1.1 on 2019-01-10 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_auto_20190110_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='number_grade',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=7),
        ),
    ]
